
title: Beschikbare noten
hero_image: images/banner.png
description: Een lijst met noten die in MicroPython kunnen worden gebruikt voor picozero
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Beschikbare noten
