title: Available notes
hero_image: images/banner.png
description: A list of notes that can be used in MicroPython alongside picozero
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Available notes
